Firefox 4

diff --git a/build/Makefile.in b/build/Makefile.in
--- a/build/Makefile.in
+++ b/build/Makefile.in
@@ -56,13 +56,24 @@ endif
 ifdef WINCE
 # We need jemalloc built before the shunt
 ifdef MOZ_MEMORY
-DIRS += wince/tools $(DEPTH)/memory/jemalloc wince/shunt
+DIRS += wince/tools \
+	$(DEPTH)/memory/jemalloc \
+	wince/shunt \
+	$(DEPTH)/memory/mozalloc \
+	$(NULL)
 else
-DIRS += wince/tools wince/shunt
+DIRS += wince/tools \
+	wince/shunt \
+	$(DEPTH)/memory/mozalloc \
+	$(NULL)
 endif
 endif
 
 DIRS += pgo
+
+ifeq (Android,$(OS_TARGET))
+  DIRS += mobile/sutagent/android
+endif
 
 include $(topsrcdir)/config/rules.mk
 
@@ -71,35 +82,55 @@ TARGET_DEPTH = ..
 include $(srcdir)/automation-build.mk
 
 _LEAKTEST_DIR = $(DEPTH)/_leaktest
+GARBAGE_DIRS += $(_LEAKTEST_DIR)
 
 _LEAKTEST_FILES =    \
 		automation.py \
-		$(CURDIR)/automationutils.py \
+		automationutils.py \
 		leaktest.py \
 		bloatcycle.html \
 		$(topsrcdir)/build/pgo/server-locations.txt \
+		$(topsrcdir)/build/pgo/favicon.ico \
+		$(topsrcdir)/build/pgo/blueprint/sample.html \
+		$(topsrcdir)/build/pgo/blueprint/elements.html \
+		$(topsrcdir)/build/pgo/blueprint/forms.html \
+		$(topsrcdir)/build/pgo/blueprint/grid.html \
+		$(topsrcdir)/build/pgo/blueprint/test.jpg \
+		$(topsrcdir)/build/pgo/blueprint/test-small.jpg \
+		$(topsrcdir)/build/pgo/blueprint/valid.png \
+		$(topsrcdir)/build/pgo/blueprint/screen.css \
+		$(topsrcdir)/build/pgo/blueprint/print.css \
+		$(topsrcdir)/build/pgo/blueprint/grid.png \
+		$(topsrcdir)/build/pgo/blueprint/fancytype-screen.css \
 		$(NULL)
 
 leaktest.py: leaktest.py.in
 	$(PYTHON) $(topsrcdir)/config/Preprocessor.py $^ > $@
 	chmod +x $@
+GARBAGE += leaktest.py
 
 libs:: $(_LEAKTEST_FILES)
 	$(INSTALL) $^ $(_LEAKTEST_DIR)
 
-ifdef ENABLE_TESTS
-# Install bloaturls.txt file for tinderbox bloat test.
-libs:: bloaturls.txt
-	$(INSTALL) $< $(DIST)/bin
+_VALGRIND_DIR = $(DEPTH)/_valgrind
+GARBAGE_DIRS += $(_VALGRIND_DIR)
 
-# Install bloatcycle.html into dist/bin/res, for auto-cycling
-# of bloaturls.txt.  This is for browsers that can't do -f
-# autocycling of URLs.
-libs:: bloatcycle.html
-	$(INSTALL) $< $(DIST)/bin/res
+_VALGRIND_FILES = \
+		$(topsrcdir)/build/valgrind/i686-redhat-linux-gnu.sup \
+		$(topsrcdir)/build/valgrind/x86_64-redhat-linux-gnu.sup \
+		$(NULL)
+
+libs:: $(_VALGRIND_FILES)
+	$(INSTALL) $^ $(_VALGRIND_DIR)
+
+ifdef ENABLE_TESTS
+libs:: $(topsrcdir)/tools/rb/fix_stack_using_bpsyms.py
+	$(INSTALL) $< $(DIST)/bin
 
 ifeq ($(OS_ARCH),Darwin)
 libs:: $(topsrcdir)/tools/rb/fix-macosx-stack.pl
+	$(INSTALL) $< $(DIST)/bin
+libs:: $(topsrcdir)/tools/rb/fix_macosx_stack.py
 	$(INSTALL) $< $(DIST)/bin
 
 # Basic unit tests for some stuff in the unify script
@@ -113,7 +144,7 @@ check::
           echo "TEST-UNEXPECTED-FAIL | build/ | unify failed to produce a universal binary!"; \
           false; \
         fi
-	@if ! test -f ./unify-test-universal; then \
+	@if test ! -f ./unify-test-universal; then \
           echo "TEST-UNEXPECTED-FAIL | build/ | unify failed to produce a universal binary!"; \
           false; \
         fi
@@ -121,7 +152,28 @@ check::
           echo "TEST-UNEXPECTED-FAIL | build/ | unify failed to produce a universal binary!"; \
           false; \
         else \
-          echo "TEST-PASS | build/ | unify produced a universal binary"; \
+          echo "TEST-PASS | build/ | unify produced a universal binary!"; \
+        fi
+# try building an x86-64 binary. if that succeeds, try unifying it
+# with an i386 binary
+	rm -f unify-test-x86_64 unify-test-universal-64
+	-$(HOST_CC) -arch x86_64 $(srcdir)/unify-test.c -o unify-test-x86_64
+	@if test -f ./unify-test-x86_64; then \
+          if ! $(srcdir)/macosx/universal/unify ./unify-test-x86_64 ./unify-test-i386 \
+            ./unify-test-universal-64; then \
+            echo "TEST-UNEXPECTED-FAIL | build/ | unify failed to produce a universal binary with a 64-bit input!"; \
+            false; \
+          fi; \
+          if test ! -f ./unify-test-universal-64; then \
+            echo "TEST-UNEXPECTED-FAIL | build/ | unify failed to produce a universal binary with a 64-bit input!"; \
+            false; \
+          fi; \
+          if ! file -b ./unify-test-universal-64 | head -n1 | grep -q "^Mach-O universal binary"; then \
+            echo "TEST-UNEXPECTED-FAIL | build/ | unify failed to produce a universal binary with a 64-bit input!"; \
+            false; \
+          else \
+            echo "TEST-PASS | build/ | unify produced a universal binary with a 64-bit input!"; \
+          fi \
         fi
 # try unifying two identical Java class files
 	rm -f unifytesta.class unifytestb.class unifytestc.class
@@ -132,7 +184,7 @@ check::
           echo "TEST-UNEXPECTED-FAIL | build/ | unify failed to unify a Java class file!"; \
           false; \
         fi
-	@if ! test -f ./unifytestc.class; then \
+	@if test ! -f ./unifytestc.class; then \
           echo "TEST-UNEXPECTED-FAIL | build/ | unify failed to unify a Java class file!"; \
           false; \
         fi
@@ -140,25 +192,25 @@ check::
           echo "TEST-UNEXPECTED-FAIL | build/ | unify failed to unify a Java class file!"; \
           false; \
         else \
-          echo "TEST-PASS | build/ | unify unified a Java class file"; \
+          echo "TEST-PASS | build/ | unify unified a Java class file!"; \
         fi
 # try unifying some files that differ only in line ordering
 	rm -rf unify-sort-test
 	mkdir unify-sort-test unify-sort-test/a unify-sort-test/b
 	printf "lmn\nabc\nxyz\n" > unify-sort-test/a/file.foo
-	printf "xyz\nlmn\nabc\n" > unify-sort-test/b/file.foo
-	printf "abc\nlmn\nxyz\n" > unify-sort-test/expected-result
+	printf "xyz\nlmn\nabc" > unify-sort-test/b/file.foo
+	printf "lmn\nabc\nxyz\n" > unify-sort-test/expected-result
 	@if ! $(srcdir)/macosx/universal/unify --unify-with-sort "\.foo$$" \
           ./unify-sort-test/a ./unify-sort-test/b \
           ./unify-sort-test/c; then \
-          echo "TEST-UNEXPECTED-FAIL | build/ | unify failed to unify files wit differing line ordering!"; \
+          echo "TEST-UNEXPECTED-FAIL | build/ | unify failed to unify files with differing line ordering!"; \
           false; \
         fi
 	@if ! diff -q ./unify-sort-test/expected-result ./unify-sort-test/c/file.foo; then \
-          echo "TEST-UNEXPECTED-FAIL | build/ | unify failed to unify files wit differing line ordering!"; \
+          echo "TEST-UNEXPECTED-FAIL | build/ | unify failed to unify files with differing line ordering!"; \
           false; \
         else \
-          echo "TEST-PASS | build/ | unify unified files with differing line orering!"; \
+          echo "TEST-PASS | build/ | unify unified files with differing line ordering!"; \
         fi
 endif
 
@@ -166,4 +218,6 @@ ifeq ($(OS_ARCH),Linux)
 libs:: $(topsrcdir)/tools/rb/fix-linux-stack.pl
 	$(INSTALL) $< $(DIST)/bin
 endif
+
+GARBAGE += $(srcdir)/automationutils.pyc
 endif # ENABLE_TESTS
